<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Description>Developer CLI for utool mods.</Description>
    <AssemblyName>utool</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UTool.ModLoader\UTool.ModLoader.csproj" />
    <ProjectReference Include="..\UTool.Pak\UTool.Pak.csproj" />
  </ItemGroup>
</Project>
