<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>UTool.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\UTool.Core\UTool.Core.csproj" />
    <ProjectReference Include="..\..\src\UTool.Infrastructure\UTool.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\UTool.ModLoader\UTool.ModLoader.csproj" />
    <ProjectReference Include="..\..\src\UTool.Pak\UTool.Pak.csproj" />
    <ProjectReference Include="..\..\src\UTool.Sdk\UTool.Sdk.csproj" />
  </ItemGroup>
</Project>
