<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Description>Developer CLI for csStratware mods.</Description>
    <AssemblyName>csmanager</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CsStratware.ModLoader\CsStratware.ModLoader.csproj" />
    <ProjectReference Include="..\CsStratware.Pak\CsStratware.Pak.csproj" />
  </ItemGroup>
</Project>
